<?php

namespace AppBundle\Repository;

/**
 * VirtualCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirtualCardRepository extends \Doctrine\ORM\EntityRepository
{
}
