app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation_test

app_routing:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /