security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        users:
            entity:
                class: AppBundle:User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: /api
            anonymous: ~
            provider: users
            guard:
                authenticators:
                    - AppBundle\Security\ApiUserAuthenticator

        main:
            anonymous: ~
            provider: users
            logout:
                path: logout
                target: login
            guard:
                authenticators:
                    - AppBundle\Security\FormUserAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_USER}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/documentation_test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest_api/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }